apps/accounts/urls.py
from django.urls import path
from apps.accounts.views import UserRegisterView, LoginView, LogOutView, UpdateUserView, PasswordResetView, UpdatePasswordView

app_name='accounts'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name = 'register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('update/', UpdateUserView.as_view(), name='update'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('update_password/', UpdatePasswordView.as_view(), name='update_password'),
    ]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('hidden_admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('resources/', include('apps.resources.urls')),
    path('', include('apps.home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
   
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from apps.common.models import BaseModel
from datetime import datetime, timedelta
import uuid
# Create your models here.
USER_STATUS_CHOICES = (
    ('free', 'FREE'),
    ('premium', 'PREMIUM'),

)


class User(AbstractUser, BaseModel):
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    photo = models.ImageField(upload_to='images/', null=True, blank=True)
    birth = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=USER_STATUS_CHOICES, default='free')
    job = models.CharField(max_length=150)
    

    
    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    @property
    def age(self):
        today = datetime.now().date()
        birth_year = self.birth.year
        day1 = self.birth.strftime("%j")
        day2 = today.strftime("%j")

        return f"{((today.year-birth_year) if day2 <= day1 else (today.year - birth_year - 1))}"
    
    def __str__(self):  
        return f"{self.email}"

email_expire_time = 5

class UserResetPassword(BaseModel):
    email = models.EmailField(blank=True, unique=False, null=True)

    def __str__(self):
        return f"{self.email}"
    

apps/accounts/forms.py
from typing import Any
from django import forms
from django.forms.widgets import TextInput, PasswordInput, EmailInput
from .models import User, UserResetPassword
from apps.accounts.utilits import CODE_LENGTH, GenerateNewPassword, send_mail_code


class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(widget=TextInput(attrs={'placeholder':'username:'}), required=False)
    email = forms.EmailField(widget=TextInput(attrs={'placeholder':'email manzilingizni kiriting:'}), required=True)
    first_name = forms.CharField(widget=TextInput(attrs={'placeholder':'ismingizni kiriting:'}), required=True)
    last_name = forms.CharField(widget=TextInput(attrs={'placeholder':'familiyangizni kiriting:'}), required=True)
    phone = forms.CharField(widget=TextInput(attrs={'placeholder':'telefon nomeringizni kiriting:'}), required=False)
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'password:'}), required=True)
    job = forms.CharField(widget=TextInput(attrs={'placeholder':'Kasbingizni kiriting:'}), required=True)
    confirm_password = forms.CharField(widget=TextInput(attrs={'placeholder':'confirm password...'}), required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'phone','job')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Bu email avval ro\'yxatdan o\'tgan, iltimos boshqa email kiriting:')
        return email
    
    def clean_confirm_password(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('confirm_password')
        if password1 != password2:
            raise forms.ValidationError('Parollar bir-biriga mos emas!!!')
        return password2
    
    def save(self, commit=True):
        password = self.cleaned_data.get('password')
        user = super().save(commit)
        user.username = self.cleaned_data.get('email')
        user.set_password(password)
        user.save()

        return user

class LoginForm(forms.Form):
    email = forms.EmailField(widget=EmailInput(attrs={'placeholder':'Emailingizni kiriting:'}), required=True)
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Password kiriting:'}), required=True)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if not email or not password:
            raise forms.ValidationError('Bo\'sh bo\'lmasligi kerak!!!')
        return self.cleaned_data
    
    
    
class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'birth')
        
        
class ResetPasswordForm(forms.ModelForm):
    email = forms.EmailField(widget=TextInput(attrs={'placeholder':'emailingizni kiriting:'}), required=True)
    
    class Meta:
        model = UserResetPassword
        fields  =('email',)
    
    def clean(self):
        email = self.cleaned_data.get('email')
        is_email = User.objects.filter(email=email).exists()
        if not is_email:
            raise forms.ValidationError("Bunday emailga ega foydalanuvchi topilmadi...")
        return self.cleaned_data

    def save(self, commit=True):
        email = self.cleaned_data.get('email')
        change_pass = super().save()
        
        new_pass = GenerateNewPassword().new_password()
        # send_mail_code(email, new_pass)
        
        print("user new password: ", new_pass)
        user = User.objects.get(email=email)
        user.set_password(new_pass)
        user.save()

        return change_pass

class UpdatePasswordForm(forms.Form):
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'eski parolni kiriting:'}), required=True)
    new_password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'yangi parol kiriting:'}), required=True)
    password_confirm = forms.CharField(widget=PasswordInput(attrs={'placeholder':'yangi parolni tasdiqlang:'}), required=True)

    def __init__(self, user, *args, **kwargs):
        super(UpdatePasswordForm, self).__init__(*args, **kwargs)
        self.user = user
        
    def clean_password(self):
        valid = self.user.check_password(self.cleaned_data['password'])
        if not valid:
            raise forms.ValidationError('Eski parolni no\'to\'g\'ri kiritdingiz. Iltimos qaytadan kiriting')
    
        if self.cleaned_data.get('new_password') != self.cleaned_data.get('password_confirm'):
            raise forms.ValidationError('Parollar bir-biriga mos kelmadi. Parollar bir xil kiritilsin.')
        return self.cleaned_data





    



    

apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from apps.accounts.models import User
from django.contrib.auth import login, logout, authenticate
from django.views import View
from apps.accounts.forms import UserRegisterForm, LoginForm, UpdateUserForm, ResetPasswordForm, UpdatePasswordForm
from .models import User, UserResetPassword
from datetime import datetime
from apps.accounts.utilits import send_mail_code
# Create your views here.


class UserRegisterView(View):
    form_class = UserRegisterForm
    def get(self, request):
        form = self.form_class()
        context = {
            'form':form
        }
        return render(request, 'accounts/register.html', context)
    
    def post(self, request):
        user_form = self.form_class(data=request.POST)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, "tizimdan muvaffaqiyatli ro'yxatdan o'tdingiz...")
            return redirect("accounts:login")

        messages.error(request, "Tizimdan ro'yxatdan o'ta olmadingiz...")
        context ={
            "form":user_form,
        }
        return render(request, 'accounts/register.html', context)
    

class LoginView(View):
    form_class = LoginForm
    
    def get(self, request):
        if request.user.is_authenticated:
            REFFERER = request.META.get('HTTP_REFERER')
            if REFFERER:
                return redirect(REFFERER)
            return redirect('home:index')
    
        
        form = self.form_class()
        context={
            'form':form
        } 
        return render(request, 'accounts/login.html', context)
    
    def post(self, request):
        user_form = self.form_class(data = request.POST)
        if user_form.is_valid():
            user = authenticate(request, email = user_form.cleaned_data['email'], password = user_form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'Siz tizimga muvaffaqiyatli kirdingiz...')
                return redirect("home:index")

            messages.error(request, "Login yoki parol noto'g'ri!!!")
            return render(request, "accounts/login.html", {'form': user_form})
        
        messages.error(request, user_form.errors)
        return render(request, "accounts/login.html", {'form': user_form})


class LogOutView(View):
    def get(self, request):
        REFFERER = request.META.get('HTTP_REFERER')
        logout(request)
        messages.success(request, 'Tizimdan muvaffaqiyatli chiqdingiz...')
        if REFFERER:
            return redirect(REFFERER)
        return redirect('home:index')


class UpdateUserView(View):
    form_class = UpdateUserForm
    def get(self , request):
        if request.user.is_authenticated:
            form = self.form_class(instance=request.user)
            context ={
                'form':form
            }
            return render(request, 'accounts/update.html', context )
        
        messages.error(request, "Tizimga kirmagansiz")
        return redirect('home:index')
    def post(self, request):
        user_form = self.form_class(data=request.POST, files=request.FILES, instance=request.user)

        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Muvaffaqiyatli yangilandi...')
            return redirect('home:index')
        
        messages.error(request, user_form.errors)
        return render(request, 'accounts/update.html', {'form':user_form})
    
    
class PasswordResetView(View):
    form_class = ResetPasswordForm
    def get(self, request):
        form = self.form_class()
        context = {
            'form':form
        }
        return render(request, "accounts/password_reset_form.html", context)
    
    def post(self, request):
        form = self.form_class(data=request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Emailingizga yangi parol yuborildi...')
            return redirect('home:index')
        
        messages.error(request, form.errors)
        return render(request, 'accounts/password_reset_form.html', {'form':form})
    
class UpdatePasswordView(View):
    form_class = UpdatePasswordForm
    def get(self, request):
        if request.user.is_authenticated:
            form = self.form_class(request.user)
            context={
                'form':form
            }
            return render(request, 'accounts/update_password.html', context)
        
    def post(self, request):
        user_form = self.form_class(data=request.POST, files=request.FILES, user=request.user)
        if user_form.is_valid():
            print(request)
            user = User.objects.filter(id=request.user.id).first()
            user.set_password(user_form.cleaned_data.get('password_confirm'))
            user.save()
            
            login(request, user)

            messages.success(request, 'Parol muvaffaqiyatli yangilandi')
            return redirect('home:index')
        messages.error(request, user_form.errors)
        return render(request, 'accounts/update_password.html', {'form':user_form})

         

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
login page
{% endblock title %}
{% block context %}

    <div class="text-login bg-login min-h-[100dvh] flex justify-center items-center">
        <div class="flex items-center sm:w-[35%] w-[90%] mx-auto login bg-white rounded-lg">
          <form class="w-full" method='POST'> {% csrf_token %}
            <h1 class="common_title">Kirish</h1>
            <div class="mb-5">
              <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
              <input type="email" id="email" name="email"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-login block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-login dark:shadow-sm-light"
                placeholder="user@gmail.com" required />
            </div>
            <div class="mb-5">
              <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your
                password</label>
              <input placeholder="******" type="password" id="password", name="password"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-login block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-login dark:shadow-sm-light"
                required />
            </div>
    
            <div class="flex items-start mb-5">
              
              <a href="{% url 'accounts:password_reset' %}" class="ms-auto text-sm font-medium text-login hover:underline dark:text-blue-500">Parolni unutdingizmi?</a>
            </div>
    
            <button type="submit"
              class="text-white bg-login hover:bg-hover_login focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm min-w-36 px-4 py-2.5 text-center">
              Kirish
            </button>
            <div class="text-sm font-medium text-gray-900 dark:text-white mt-5 mb-5">
              Ro'yxatdan o'tmaganmisiz?
              <a href="{% url 'accounts:register' %}" class="text-login hover:underline">Ro'yxatdan o'tish</a>
            </div>
          </form>
        </div>
      </div>
      
{% endblock context %}

templates/accounts/password_reset_email.html
{% extends "base.html" %}

{% block title %}

sending password page

{% endblock title %}
{% block content %}
    <p>Salom,</p>
    <p>Sizning parolingiz qayta tiklandi. Yangi parol: <strong>{{ password }}</strong></p>
    <p>Siz Salomatlik maktabi kutubxona tizimiga bundan buyog'iga shu parol bilan kira olasiz. Tizimdan parolingizni o'zgartirib olishingiz mumkin....</p>
    <p>Yana savollaringiz bo'lsa biz bilan bog'lanishingiz mumkin.</p>
    <p>Phone: +998972001426 </p>

{% endblock content %}

templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% block title %}
Forgot your password?
{% endblock title %}

{% block context %}

    <div class="text-login bg-login min-h-[70dvh] flex justify-center items-center">
        <div class="flex items-center sm:w-[35%] w-[90%] mx-auto login bg-white rounded-lg">
          <form class="w-full" method='POST'>
            {% csrf_token %}
            <h1 class="common_title">Parolni tiklash</h1>
            <div class="mb-5">
              <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email kiriting</label>
              <input type="email" id="email" name='email'
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-login block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-login dark:shadow-sm-light"
                placeholder="user@gmail.com" required />
            </div>
    
            <button type="submit"
              class="text-white bg-login hover:bg-hover_login focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm min-w-36 px-4 py-2.5 text-center">
              Davom etish
            </button>
            <div class="text-sm font-medium text-gray-900 dark:text-white mt-5 mb-5">
              <a href="{% url 'accounts:register' %}" class="text-login hover:underline">Register</a> 
              |
              <a href="{% url 'accounts:login' %}" class="text-login hover:underline">Log In</a>
            </div>
          </form>
        </div>
      </div>
    
{% endblock context %}

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}
register page
{% endblock title %}
{% block context %}

        <div class="text-login bg-login min-h-[100dvh] flex justify-center items-center">

            <div class="flex items-center sm:max-w-2xl w-[80%] mx-auto login bg-white rounded-lg">
              <form class="w-full sm:pb-6 pb-3"  method='POST'>
                {% csrf_token %}
                <h1 class="common_title">Ro'yxatdan o'tish</h1>
                <div class="grid md:grid-cols-2 md:gap-6">
                  <div class="relative z-0 w-full sm:mb-5 mb-2 group">
                    <input type="text" name="first_name" id="first_name"
                      class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600  focus:outline-none focus:ring-0 focus:border-login peer"
                      placeholder=" " required />
                    <label for="first_name"
                      class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-login  peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">First
                      name</label>
                  </div>
                  <div class="relative z-0 w-full sm:mb-5 mb-2 group">
                    <input type="text" name="last_name" id="last_name"
                      class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600  focus:outline-none focus:ring-0 focus:border-login peer"
                      placeholder=" " required />
                    <label for="last_name"
                      class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-login  peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Last
                      name</label>
                  </div>
                </div>
                <div class="relative z-0 w-full sm:mb-5 mb-2 group">
                  <input type="text" name="job" id="job"
                    class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600  focus:outline-none focus:ring-0 focus:border-login peer"
                    placeholder=" " required />
                  <label for="job"
                    class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-login  peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Job
                    </label>
                </div>
                <div class="relative z-0 w-full sm:mb-5 mb-2 group">
                  <input type="email" name="email" id="email"
                    class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600  focus:outline-none focus:ring-0 focus:border-login peer"
                    placeholder=" " required />
                  <label for="email"
                    class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-login  peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email
                    address</label>
                </div>
          
                
                <div class="grid md:grid-cols-2 md:gap-6">
                <div class="relative z-0 w-full sm:mb-5 mb-2 group">
                  <input type="password" name="password" id="password"
                    class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600  focus:outline-none focus:ring-0 focus:border-login peer"
                    placeholder=" " required />
                  <label for="password"
                    class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-login  peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Password</label>
                </div>

                <div class="relative z-0 w-full sm:mb-5 mb-2 group">
                  <input type="password" name="confirm_password" id="confirm_password"
                    class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600  focus:outline-none focus:ring-0 focus:border-login peer"
                    placeholder=" " required />
                  <label for="confirm_password"
                    class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-login  peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Confirm
                    password</label>
                </div>

        
           
                 
                </div>
                <button type="submit"
                  class="text-white bg-login hover:hover_login focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm min-w-36 px-4 py-2.5 text-center">Ro'yxatdan
                  o'tish</button>
                <div class="text-sm font-medium text-gray-900 dark:text-white mt-5">
                  Ro'yxatdan o'tganmisiz? <a href="{% url 'accounts:login' %}" class="text-login hover:underline">Kirish</a>
                </div>
        
              </form>
            </div>
          </div>
{% endblock context%}

templates/accounts/update_password.html
{% extends 'base.html' %}
{% block title %}
Update password
{% endblock title %}

{% block context %}

    <h1>yangi parol o'rnatish</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="tasdiqlash" style="color: blue; background-color: aqua;">
    </form>

    
{% endblock context %}